accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'accounts'

urlpatterns = [
    path('', views.account_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

c_data/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView, DetailView

app_name = 'c_data'

urlpatterns = [
    path('', views.index, name='index'),
    path('user/<int:pk>/', views.user_detail, name='user_detail'),
    path('user/<int:pk>/profile', views.profile, name='profile'),
    path('user/<int:pk>/list', views.list, name='list'),
    path('user/<int:pk>/new', views.new_data, name='new_data'),
    path('user/<int:pk>/detail/<int:CustomerData_id>',
         views.detail, name='detail'),
    path('user/<int:pk>/conditions/<int:CustomerData_id>',
         views.conditions, name='conditions'),
    path('user/<int:pk>/prospect', views.prospect, name='prospect'),
    path('user/<int:pk>/progress', views.progress, name='progress'),
    path('user/<int:pk>/budget_control',
         views.budget_control, name='budget_control'),
    path('user/<int:pk>/data', views.data, name='data'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('accounts.urls', namespace='accounts')),
    path('', include('c_data.urls', namespace='c_data')),
    path('reservation', include('reservation.urls', namespace='reservation')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reservation/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView, DetailView
from django.contrib.auth.decorators import login_required

app_name = 'reservation'

urlpatterns = [
    path('/month', login_required(views.Index.as_view()), name='index'),
    path('/month/<int:year>/<int:month>/<int:day>/',
         login_required(views.Index.as_view()), name='index'),
    path('/month/create', login_required(views.MonthCalendar.as_view()), name='create'),
    path('/month/create/<int:year>/<int:month>/<int:day>/',
         login_required(views.MonthCalendar.as_view()), name='create'),
    path('/month/update/<int:pk>',
         login_required(views.ScheduleUpdateView.as_view()), name='update'),
    path('/month/delete/<int:pk>',
         login_required(views.ScheduleDeleteView.as_view()), name='delete'),
]

reservation/models.py
import datetime
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    """スケジュール"""
    user_id = models.IntegerField('ユーザーID')
    space_name = models.CharField('設備名', max_length=20)
    purpose = models.CharField('目的', max_length=255, blank=True)
    description = models.CharField('詳細', max_length=255, blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    repeat = models.IntegerField('繰り返し', blank=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.description

reservation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views import generic
from . import mixins
from .forms import ScheduleForm
from .models import Schedule
from .lib import TimeScheduleBS4
from .lib_index import TimeSchedule
from django.utils.safestring import mark_safe
import datetime
import calendar
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
# Create your views here.


class Index(mixins.MonthCalendarMixin, generic.TemplateView):
    template_name = 'reservation/index.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_id'] = self.request.user
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        schedules_a = Schedule.objects.filter(
            space_name='Aスペース', date=context['month_current']).order_by('start_time')
        schedules_b = Schedule.objects.filter(
            space_name='Bスペース', date=context['month_current']).order_by('start_time')
        schedules_c = Schedule.objects.filter(
            space_name='Cスペース', date=context['month_current']).order_by('start_time')
        schedules_i = Schedule.objects.filter(
            space_name='印鑑', date=context['month_current']).order_by('start_time')
        time_schedule = TimeSchedule(step=15, minute_height=1)
        context['time_schedule_a'] = mark_safe(
            time_schedule.format_schedule_a(schedules_a, context['user_id'])
        )
        context['time_schedule_b'] = mark_safe(
            time_schedule.format_schedule_b(schedules_b, context['user_id'])
        )
        context['time_schedule_c'] = mark_safe(
            time_schedule.format_schedule_c(schedules_c, context['user_id'])
        )
        context['time_schedule_i'] = mark_safe(
            time_schedule.format_schedule_i(schedules_i, context['user_id'])
        )

        return context


class MonthCalendar(mixins.MonthCalendarMixin, generic.CreateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'reservation/create.html'
    model = Schedule
    date_field = 'date'
    form_class = ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        schedules_a = Schedule.objects.filter(
            space_name='Aスペース', date=context['month_current']).order_by('start_time')
        schedules_b = Schedule.objects.filter(
            space_name='Bスペース', date=context['month_current']).order_by('start_time')
        schedules_c = Schedule.objects.filter(
            space_name='Cスペース', date=context['month_current']).order_by('start_time')
        schedules_i = Schedule.objects.filter(
            space_name='印鑑', date=context['month_current']).order_by('start_time')
        time_schedule = TimeScheduleBS4(step=15, minute_height=1)
        context['time_schedule_time'] = mark_safe(
            time_schedule.format_schedule_time(schedules_a)
        )
        context['time_schedule_a'] = mark_safe(
            time_schedule.format_schedule_a(schedules_a)
        )
        context['time_schedule_b'] = mark_safe(
            time_schedule.format_schedule_b(schedules_b)
        )
        context['time_schedule_c'] = mark_safe(
            time_schedule.format_schedule_c(schedules_c)
        )
        context['time_schedule_i'] = mark_safe(
            time_schedule.format_schedule_i(schedules_i)
        )
        return context

    def form_valid(self, form):
        today = datetime.date(
            int(self.request.POST['year']),
            int(self.request.POST['month']),
            int(self.request.POST['day'])
        )
        after_one_year = today + relativedelta(months=12)
        day_count = after_one_year-today
        if self.request.POST['repeat'] == '1':
            posts = []
            _, lastday = calendar.monthrange(
                int(self.request.POST['year']), int(self.request.POST['month']))
            for i in range(lastday - int(self.request.POST['day'])+1):
                post = Schedule(
                    user_id=self.request.POST['user_id'],
                    space_name=self.request.POST['space_name'],
                    purpose=self.request.POST['purpose'],
                    description=self.request.POST['description'],
                    start_time=datetime.time(
                        int(self.request.POST['start_hour']),
                        int(self.request.POST['start_minute'])
                    ),
                    end_time=datetime.time(
                        int(self.request.POST['end_hour']),
                        int(self.request.POST['end_minute'])
                    ),
                    date=datetime.date(
                        int(self.request.POST['year']),
                        int(self.request.POST['month']),
                        int(self.request.POST['day'])
                    ) + timedelta(days=i),
                    repeat=1,
                )
                posts.append(post)
            Schedule.objects.bulk_create(posts)
            return redirect('reservation:index')
        elif self.request.POST['repeat'] == '2':
            posts = []
            for i in range(0, day_count.days, 7):
                post = Schedule(
                    user_id=self.request.POST['user_id'],
                    space_name=self.request.POST['space_name'],
                    purpose=self.request.POST['purpose'],
                    description=self.request.POST['description'],
                    start_time=datetime.time(
                        int(self.request.POST['start_hour']),
                        int(self.request.POST['start_minute'])
                    ),
                    end_time=datetime.time(
                        int(self.request.POST['end_hour']),
                        int(self.request.POST['end_minute'])
                    ),
                    date=datetime.date(
                        int(self.request.POST['year']),
                        int(self.request.POST['month']),
                        int(self.request.POST['day'])
                    ) + timedelta(days=i),
                    repeat=2,
                )
                posts.append(post)
            Schedule.objects.bulk_create(posts)
            return redirect('reservation:index')
        else:
            date = datetime.date(
                int(form.cleaned_data['year']),
                int(form.cleaned_data['month']),
                int(form.cleaned_data['day'])
            )
            schedule = form.save(commit=False)
            schedule.date = date
            schedule.user_id = self.request.user.id
            schedule.start_time = datetime.time(
                int(form.cleaned_data['start_hour']),
                int(form.cleaned_data['start_minute'])
            )
            schedule.end_time = datetime.time(
                int(form.cleaned_data['end_hour']),
                int(form.cleaned_data['end_minute'])
            )
            schedule.save()
            return redirect('reservation:index', year=date.year, month=date.month, day=date.day)


class ScheduleUpdateView(generic.UpdateView):
    model = Schedule
    form_class = ScheduleForm
    ate_field = 'date'
    template_name = 'reservation/update.html'
    success_url = 'reservation/index.html'

    def get_context_data(self, **kwargs):
        queryset = Schedule.objects.get(id=self.kwargs['pk'])
        context = super().get_context_data(**kwargs)
        context['form'] = ScheduleForm(initial={
            'space_name': queryset.space_name,
            'purpose': queryset.purpose,
            'description': queryset.description,
            'year': queryset.date.year,
            'month': queryset.date.month,
            'day': queryset.date.day,
            'start_hour': queryset.start_time.hour,
            'start_minute': queryset.start_time.minute,
            'end_hour': queryset.end_time.hour,
            'end_minute': queryset.end_time.minute,
            'repeat': queryset.repeat,
        })
        return context

    def form_valid(self, form):
        date = datetime.date(
            int(form.cleaned_data['year']),
            int(form.cleaned_data['month']),
            int(form.cleaned_data['day'])
        )
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.user_id = self.request.user.id
        schedule.start_time = datetime.time(
            int(form.cleaned_data['start_hour']),
            int(form.cleaned_data['start_minute'])
        )
        schedule.end_time = datetime.time(
            int(form.cleaned_data['end_hour']),
            int(form.cleaned_data['end_minute'])
        )
        schedule.save()
        return redirect('reservation:index', year=date.year, month=date.month, day=date.day)


class ScheduleDeleteView(generic.DeleteView):
    model = Schedule
    template_name = 'reservation/delete.html'
    success_url = '/reservation/month'

    def get_context_data(self, **kwargs):
        queryset = Schedule.objects.get(id=self.kwargs['pk'])
        context = super().get_context_data(**kwargs)
        context['space_name'] = queryset.space_name
        context['purpose'] = queryset.purpose
        context['description'] = queryset.description
        context['year'] = queryset.date.year
        context['month'] = queryset.date.month
        context['day'] = queryset.date.day
        context['start_hour'] = queryset.start_time.hour
        context['start_minute'] = queryset.start_time.minute
        context['end_hour'] = queryset.end_time.hour
        context['end_minute'] = queryset.end_time.minute
        context['repeat'] = queryset.repeat
        return context

reservation/templates/reservation/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>結家アプリ</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'c_data/images/icons/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'c_data/images/icons/favicon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'c_data/images/icons/favicon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'c_data/images/icons/favicon-114x114.png' %}">
    <script src="https://ajaxzip3.github.io/ajaxzip3.js" charset="UTF-8"></script>
    <!--Loading bootstrap css-->
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,700">
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/jquery-ui-1.10.4.custom.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/font-awesome.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/animate.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/all.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/main.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/style-responsive.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/zabuto_calendar.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/pace.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'c_data/styles/jquery.news-ticker.css' %}">

    <style>
        .minute-wrapper {
            text-align: center;
            border: 1px solid darkgray;
        }

        .hour-name {
            padding: 10px;
            text-align: center;
            border: 1px solid darkgray;
        }

        .just-hour {
            border-top: 2px solid darkgray;
        }

        .space_css {
            border-bottom: 1px solid darkgray;
        }


    </style>
</head>

<body>
  <div>
      <!--BEGIN BACK TO TOP-->
      <a id="totop" href="#"><i class="fa fa-angle-up"></i></a>
      <!--END BACK TO TOP-->
      <!--BEGIN TOPBAR-->
      <div id="header-topbar-option-demo" class="page-header-topbar">
          <nav id="topbar" role="navigation" style="margin-bottom: 0;" data-step="3" class="navbar navbar-default navbar-static-top">
              <div class="navbar-header">
                  <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                  <a id="logo" href="#" class="navbar-brand"><span class="fa fa-rocket"></span><span class="logo-text">設備予約</span><span style="display: none" class="logo-text-icon">µ</span></a></div>
                  <div class="topbar-main"><a id="menu-toggle" href="#" class="hidden-xs"><i class="fa fa-bars"></i></a>
                  <ul class="nav navbar navbar-top-links navbar-right mbn">
                      <li class="dropdown topbar-user"><a data-hover="dropdown" href="#" class="dropdown-toggle">&nbsp;<span class="hidden-xs">{{ user.first_name }} {{ user.last_name }}</span>&nbsp;<span class="caret"></span></a>
                          <ul class="dropdown-menu dropdown-user pull-right">
                              <li><a href="{% url 'c_data:profile' pk=user.id %}"><i class="fa fa-user"></i>プロフィール</a></li>
                              <li class="divider"></li>
                              <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-key"></i>ログアウト</a></li>
                          </ul>
                      </li>
                  </ul>
              </div>
          </nav>
      </div>
      <!--END TOPBAR-->

  {% block content %}{% endblock %}

  </div>

    <script src="{% static 'c_data/script/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'c_data/script/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'c_data/script/jquery-ui.js' %}"></script>
    <script src="{% static 'c_data/script/bootstrap.min.js' %}"></script>
    <script src="{% static 'c_data/script/bootstrap-hover-dropdown.js' %}"></script>
    <script src="{% static 'c_data/script/html5shiv.js' %}"></script>
    <script src="{% static 'c_data/script/respond.min.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.cookie.js' %}"></script>
    <script src="{% static 'c_data/script/icheck.min.js' %}"></script>
    <script src="{% static 'c_data/script/custom.min.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.news-ticker.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.menu.js' %}"></script>
    <script src="{% static 'c_data/script/pace.min.js' %}"></script>
    <script src="{% static 'c_data/script/holder.js' %}"></script>
    <script src="{% static 'c_data/script/responsive-tabs.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.flot.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.flot.categories.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.flot.tooltip.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.flot.fillbetween.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'c_data/script/jquery.flot.spline.js' %}"></script>
    <script src="{% static 'c_data/script/zabuto_calendar.min.js' %}"></script>
    <script src="{% static 'c_data/script/index.js' %}"></script>
    <!--LOADING SCRIPTS FOR CHARTS-->
    <script src="{% static 'c_data/script/highcharts.js' %}"></script>
    <script src="{% static 'c_data/script/data.js' %}"></script>
    <script src="{% static 'c_data/script/drilldown.js' %}"></script>
    <script src="{% static 'c_data/script/exporting.js' %}"></script>
    <script src="{% static 'c_data/script/highcharts-more.js' %}"></script>
    <script src="{% static 'c_data/script/charts-highchart-pie.js' %}"></script>
    <script src="{% static 'c_data/script/charts-highchart-more.js' %}"></script>
    <!--CORE JAVASCRIPT-->
    <script src="{% static 'c_data/script/main.js' %}"></script>
    <script>        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-145464-12', 'auto');
        ga('send', 'pageview');


    </script>
    <script>
        $(function() {
            $('[data-toggle="tooltip"]').tooltip('show');
        });
        $('.time').bootstrapMaterialDatePicker({ date: false });
    </script>
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>

</body>
</html>

reservation/templates/reservation/delete.html
{% extends 'reservation/base.html' %}

{% block content %}
<div id="wrapper">
<!--BEGIN SIDEBAR MENU-->
<nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
    <div class="sidebar-collapse menu-scroll">
        <ul id="side-menu" class="nav">
            <div class="clearfix"></div>
            <li><a href="{% url 'reservation:index' %}"><i class="fa fa-th-list fa-fw">
                  <div class="icon-bg bg-blue"></div>
              </i><span class="menu-title">TOP</span></a>
            </li>
            <li><a href="{% url 'c_data:user_detail' pk=user.id %}"><i class="fa fa-desktop fa-fw">
                  <div class="icon-bg bg-green"></div>
              </i><span class="menu-title">顧客管理表へ</span></a>
            </li>
        </ul>
    </div>
</nav>
<!--END SIDEBAR MENU-->
  <div id="page-wrapper">
    <div class="page-content">
      <div class="row">
        <div class="col-lg-12">
          <div class="col-md-5 col-sm-12">
            <div class="panel panel-grey">
                <div class="panel-heading">この予定を削除しますか？</div>
                  <div class="panel-body">
                    <table class="table table-hover">
                      <tbody style="text-align:center">
                          <tr class="active">
                            <td class="col-sm-6">設備</td>
                            <td class="col-sm-6">{{ space_name }}</td>
                          </tr>
                          <tr class="active">
                              <td class="col-sm-6">用途</td>
                              <td class="col-sm-6">{{ purpose }}</td>
                          </tr>
                          <tr class="active">
                              <td class="col-sm-6">詳細</td>
                              <td class="col-sm-6">{{ description }}</td>
                          </tr>
                          <tr class="active">
                              <td class="col-sm-6">日付</td>
                              <td class="col-sm-6">{{ year }}年{{month}}月{{day}}日</td>
                          </tr>
                          <tr class="active">
                              <td class="col-sm-6">開始</td>
                              <td class="col-sm-6">{{ start_hour }}時{{start_minute}}分</td>
                          </tr>
                          <tr class="active">
                              <td class="col-sm-6">終了</td>
                              <td class="col-sm-6">{{ end_hour }}時{{end_minute}}分</td>
                          </tr>
                      </tbody>
                      </form>
                    </table>
                    <br><br><br>
                      <form method="post">
                        <div style="text-align:center;">
                          <button class="btn btn-danger">削除する</button>
                        </div>
                        {% csrf_token %}
                      </form>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

reservation/templates/reservation/index.html
{% extends 'reservation/base.html' %}
{% load static %}
{% block content %}
<div id="wrapper">
<!--BEGIN SIDEBAR MENU-->
<nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
    <div class="sidebar-collapse menu-scroll">
        <ul id="side-menu" class="nav">
            <div class="clearfix"></div>
            <li><a href="{% url 'reservation:create' %}"><i class="fa fa-th-list fa-fw">
                  <div class="icon-bg bg-blue"></div>
              </i><span class="menu-title">新規登録</span></a>
            </li>
            <li><a href="{% url 'c_data:user_detail' pk=user.id %}"><i class="fa fa-desktop fa-fw">
                  <div class="icon-bg bg-green"></div>
              </i><span class="menu-title">顧客管理表へ</span></a>
            </li>
        </ul>
    </div>
</nav>
<!--END SIDEBAR MENU-->
<div id="page-wrapper">
  <div class="page-content">
      <div class="row">
        <div class="col-lg-12">
            <div class="col-md-5 col-sm-12">
                <div class="panel panel-red">
                    <div class="panel-heading">Topics</div>
                    <div class="panel-body">
                        <div id="context1">
                          <a href="https://docs.google.com/spreadsheets/d/1h5hoHpGi7xqxYTJHtORzcd9vAtCe_UBB9zbogKt44kg/edit?usp=sharing" target="blank">
                          <h3> 💴 第９期  17口座入金リスト💰</h3>
                          </a>
                        </div>
                        <div id="context2">
                          <a href="https://docs.google.com/spreadsheets/d/10Z7BxIlcDP178FbIGQQWIT7uu4ENMd80EoEVn86icWU/edit#gid=486033444​" target="blank">
                          <h3>💻MTG・レク飲み会出欠表🍻 </h3>
                          </a>
                        </div>
                        <div id="context3">
                          <a href="https://docs.google.com/spreadsheets/d/1aFlEIZKgi53FRf2ePEiVT4-T3bSAtlAogbigPLLUH5c/edit?usp=sharing" target="blank">
                          <h3 style="display:inline-block;">🙆管理物件一覧表🍻 </h3>
                          </a>
                          <p style="display:inline-block;color:red;">※物件確認の時に見てね！</p>
                        </div>
                        <br>
                        <div id="bccoment">
                          <img src="{% static 'c_data/dog/bcdog.png' %}" style="float:left;">
                          <p style="color:red;font-size:20px;">来客以外はスペース予約基本禁止です！！</p>
                          <span>(※会社公認のMTG除く)</span>
                        </div>
                        <div id="bc_footer">
                          <h4>業者対応はなるべく外でおねがいします☆</h4>
                        </div>
                    </div>
                </div>
                <div class="panel panel-green">
                    <div class="panel-heading">カレンダー</div>
                    <div class="panel-body">
                      {% include 'reservation/month_index.html' %}
                    </div>
                </div>
            </div>
            <div class="col-md-7 col-sm-12">
              <div class="panel panel-grey">
                    <div class="panel-heading">
                      {{ month_current | date:"Y年m月d日" }}
                    </div>
                    <div class="panel-body">
                        <!-- Aスペ -->
                        <form method="POST" action="" onSubmit="return check()">
                {% csrf_token %}
                        <div class="col-xs-3" style="padding:0;">
                           {{ time_schedule_a }}
                        </div>
                        </form>
                        <!-- Bスペ -->
                        <div class="col-xs-3" style="padding:0;">
                          {{ time_schedule_b }}
                        </div>
                        <!-- Cスペ -->
                        <div class="col-xs-3" style="padding:0;">
                          {{ time_schedule_c }}
                        </div>
                        <!-- 印鑑 -->
                        <div class="col-xs-3" style="padding:0;">
                          {{ time_schedule_i }}
                        </div>
                      </div><br>
                  </div>
              </div>
            </div>

        </div>
      </div>
  </div>
</div>


</div>

<script>


function check(){

	if(window.confirm('削除してよろしいですか？')){ // 確認ダイアログを表示

		return true; // 「OK」時は送信を実行

	}
	else{ // 「キャンセル」時の処理

		window.alert('キャンセルされました'); // 警告ダイアログを表示
		return false; // 送信を中止

	}

}
</script>

{% endblock %}

reservation/templates/reservation/month.html
    <a href="{% url 'reservation:create' month_previous.year month_previous.month month_previous.day %}" class="text-info">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'reservation:create' month_next.year month_next.month month_next.day %}" class="text-info">次月</a>
    <a href="{% url 'reservation:create' now.year now.month now.day %}" class="text-info" style="float:right;">今日</a>

    <br><br>

    <table class="table table-bordered" style="table-layout:fixed;">
        <thead>
        <tr>
            {% for w in week_names %}
              {% if w == '土' %}
                  <th class="bg-info" style="text-align:center">{{ w }}</th>
              {% elif w == '日' %}
                  <th class="bg-danger" style="text-align:center">{{ w }}</th>
              {% else %}
                  <th style="text-align:center;background-color:darkgray;color:white">{{ w }}</th>
              {% endif %}
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month != day.month %}
                  <a href="{% url 'reservation:create' day.year day.month day.day %}">
                    {{ day | date:"m/d" }}
                  </a>
                {% else %}
                  <a href="{% url 'reservation:create' day.year day.month day.day %}">
                    {{ day.day }}
                  </a>
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>