accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'accounts'

urlpatterns = [
    path('', views.account_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

c_data/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView, DetailView

app_name = 'c_data'

urlpatterns = [
    path('', views.index, name='index'),
    path('user/<int:pk>/', views.user_detail, name='user_detail'),
    path('user/<int:pk>/profile', views.profile, name='profile'),
    path('user/<int:pk>/list', views.list, name='list'),
    path('user/<int:pk>/new', views.new_data, name='new_data'),
    path('user/<int:pk>/detail/<int:CustomerData_id>',
         views.detail, name='detail'),
    path('user/<int:pk>/conditions/<int:CustomerData_id>',
         views.conditions, name='conditions'),
    path('user/<int:pk>/prospect', views.prospect, name='prospect'),
    path('user/<int:pk>/progress', views.progress, name='progress'),
    path('user/<int:pk>/budget_control',
         views.budget_control, name='budget_control'),
    path('user/<int:pk>/data', views.data, name='data'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('accounts.urls', namespace='accounts')),
    path('', include('c_data.urls', namespace='c_data')),
    path('reservation', include('reservation.urls', namespace='reservation')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       #htmlの表示を変更可能にします
       self.fields['username'].widget.attrs['class'] = 'form-control'
       self.fields['password'].widget.attrs['class'] = 'form-control'

class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    class Meta:
       model = User
       fields = ("username", "password1", "password2",)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, CreateView, View
from . forms import UserCreateForm, LoginForm


# Create your views here.

class IndexView(TemplateView):
    template_name = "accounts/index.html"


index = IndexView.as_view()

# ログイン


class Account_login(View):
    # template_name = "accounts/login.html"
    def post(self, request, *arg, **kwargs):
        if 'c_data' in request.POST:
            form = LoginForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                user = User.objects.get(username=username)
                login(request, user)
                login_user = request.user
                return redirect('c_data:user_detail', pk=login_user.id)
        if 'reservation' in request.POST:
            form = LoginForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                user = User.objects.get(username=username)
                login(request, user)
                login_user = request.user
                return redirect('reservation:index')
        return render(request, 'accounts/login.html', {'form': form, })

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'accounts/login.html', {'form': form, })


account_login = Account_login.as_view()

# 新規作成


class Create_Account(CreateView):
    def post(self, request, *args, **kwargs):
        form = UserCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            # フォームから'username'を読み取る
            username = form.cleaned_data.get('username')
            # フォームから'password1'を読み取る
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/users/{}/'.format(user.id))
        return render(request, 'create.html', {'form': form, })

    def get(self, request, *args, **kwargs):
        form = UserCreateForm(request.POST)
        return render(request, 'create.html', {'form': form, })


create_account = Create_Account.as_view()

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <title>Dashboard | Dashboard</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'accounts/images/icons/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'accounts/images/icons/favicon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'accounts/images/icons/favicon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'accounts/images/icons/favicon-114x114.png' %}">
    <!--Loading bootstrap css-->
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,700">
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/jquery-ui-1.10.4.custom.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/font-awesome.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/animate.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/all.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/main.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/style-responsive.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/zabuto_calendar.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/pace.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/styles/jquery.news-ticker.css' %}">
</head>

<body>
  <div>
      <!--BEGIN BACK TO TOP-->
      <a id="totop" href="#"><i class="fa fa-angle-up"></i></a>
      <!--END BACK TO TOP-->
      <!--BEGIN TOPBAR-->
      <div id="header-topbar-option-demo" class="page-header-topbar">
          <nav id="topbar" role="navigation" style="margin-bottom: 0;" data-step="3" class="navbar navbar-default navbar-static-top">
              <div class="navbar-header">
                  <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                  <a id="logo" href="#" class="navbar-brand"><span class="fa fa-rocket"></span><span class="logo-text">結家ツール</span><span style="display: none" class="logo-text-icon">µ</span></a></div>
              <div class="topbar-main"><a id="menu-toggle" href="#" class="hidden-xs"></a></div>
          </nav>
      </div>
      <!--END TOPBAR-->

  {% block content %}{% endblock %}

  </div>

    <script src="{% static 'accounts/script/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'accounts/script/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'accounts/script/jquery-ui.js' %}"></script>
    <script src="{% static 'accounts/script/bootstrap.min.js' %}"></script>
    <script src="{% static 'accounts/script/bootstrap-hover-dropdown.js' %}"></script>
    <script src="{% static 'accounts/script/html5shiv.js' %}"></script>
    <script src="{% static 'accounts/script/respond.min.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.cookie.js' %}"></script>
    <script src="{% static 'accounts/script/icheck.min.js' %}"></script>
    <script src="{% static 'accounts/script/custom.min.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.news-ticker.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.menu.js' %}"></script>
    <script src="{% static 'accounts/script/pace.min.js' %}"></script>
    <script src="{% static 'accounts/script/holder.js' %}"></script>
    <script src="{% static 'accounts/script/responsive-tabs.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.flot.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.flot.categories.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.flot.tooltip.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.flot.fillbetween.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'accounts/script/jquery.flot.spline.js' %}"></script>
    <script src="{% static 'accounts/script/zabuto_calendar.min.js' %}"></script>
    <script src="{% static 'accounts/script/index.js' %}"></script>
    <!--LOADING SCRIPTS FOR CHARTS-->
    <script src="{% static 'accounts/script/highcharts.js' %}"></script>
    <script src="{% static 'accounts/script/data.js' %}"></script>
    <script src="{% static 'accounts/script/drilldown.js' %}"></script>
    <script src="{% static 'accounts/script/exporting.js' %}"></script>
    <script src="{% static 'accounts/highcharts-more.js' %}"></script>
    <script src="{% static 'accounts/script/charts-highchart-pie.js' %}"></script>
    <script src="{% static 'accounts/script/charts-highchart-more.js' %}"></script>
    <!--CORE JAVASCRIPT-->
    <script src="{% static 'accounts/script/main.js' %}"></script>
    <script>        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-145464-12', 'auto');
        ga('send', 'pageview');


    </script>
</body>
</html>

accounts/templates/accounts/create.html
{% extends 'accounts/base.html' %}

{% load static %}
{% block content %}

    <form method="POST" action="{% url 'create_account' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password1 }}
      {{ form.password1.errors }}
      <label>パスワード(確認)</label>
      {{ form.password2 }}
      {{ form.password2.errors }}
      <button type = "submit">登録</button>
    </form>

{% endblock %}

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="page-form">
        <p>準備中</p>

        <a href="{% url 'accounts:login' %}" role="button" class="btn btn-default">ログイン</a>
        <a href="#" role="button" class="btn btn-default">新規アカウト作成</a>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% load static %}
{% block content %}


    <div class="page-form">
        <div class="panel panel-blue">
            <div class="panel-body pan">
                <form method="POST" action="{% url 'accounts:login' %}" class="form-horizontal">
                  {% csrf_token %}
                <div class="form-body pal">
                    <div class="col-md-12 text-center">
                        <h1 style="margin-top: -90px; font-size: 48px;">
                            ログイン</h1>
                        <br />
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <img src="{% static 'accounts/images/avatar/profile-pic.png' %}" class="img-responsive" style="margin-top: -35px;" />
                        </div>
                        {% if form.errors  %}
                        <div class="col-md-9 text-center">
                            <p>ユーザーID, パスワードが一致しません。</p>
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="inputName" class="col-md-3 control-label">
                            UserID:</label>
                        <div class="col-md-9">
                            <div class="input-icon right">
                                <i class="fa fa-user"></i>
                                {{ form.username }}
                                {{ form.username.errors }}
                                </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="col-md-3 control-label">
                            Password:</label>
                        <div class="col-md-9">
                            <div class="input-icon right">
                                <i class="fa fa-lock"></i>
                                {{ form.password }}
                                {{ form.password.errors }}
                              </div>
                        </div>
                    </div>
                    <div class="form-group mbn">
                        <div class="col-lg-12" align="right">
                            <div class="form-group mbn">
                                <div class="col-lg-3">
                                    &nbsp;
                                </div>
                                <div class="col-lg-9">
                                  <button type="submit" name="reservation" class="btn btn-default">設備予約へ</button>
                                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                  <button type="submit" name="c_data" class="btn btn-default">顧客管理表へ</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    </form>
                </div>
                </form>
            </div>
        </div>
        <!-- <div class="col-lg-12 text-center">
            <p>
                Forgot Something ?
            </p>
        </div> -->
    </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'c_data/base.html' %}

{% block content %}
<h2>ユーザー登録</h2>

<form method="post" action="{% url 'c_data:signup' %}">{% csrf_token %}
    <label>ユーザー名</label>
    {{ form.username }}
    {{ form.username.errors }}
    <br>
    <label>パスワード</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
    <br>
    <label>パスワード(確認)</label>
    {{ form.password2 }}
    {{ form.password2.errors }}
    <br>
    <input type="submit" value="登録する">
</form>

<p><a href="{% url 'c_data:login' %}">ログインはこちら</a></p>

{% endblock %}