accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'accounts'

urlpatterns = [
    path('', views.account_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

c_data/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView, DetailView

app_name = 'c_data'

urlpatterns = [
    path('', views.index, name='index'),
    path('user/<int:pk>/', views.user_detail, name='user_detail'),
    path('user/<int:pk>/profile', views.profile, name='profile'),
    path('user/<int:pk>/list', views.list, name='list'),
    path('user/<int:pk>/new', views.new_data, name='new_data'),
    path('user/<int:pk>/detail/<int:CustomerData_id>',
         views.detail, name='detail'),
    path('user/<int:pk>/conditions/<int:CustomerData_id>',
         views.conditions, name='conditions'),
    path('user/<int:pk>/prospect', views.prospect, name='prospect'),
    path('user/<int:pk>/progress', views.progress, name='progress'),
    path('user/<int:pk>/budget_control',
         views.budget_control, name='budget_control'),
    path('user/<int:pk>/data', views.data, name='data'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('accounts.urls', namespace='accounts')),
    path('', include('c_data.urls', namespace='c_data')),
    path('reservation', include('reservation.urls', namespace='reservation')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

c_data/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import CustomerData, MusubiyaUser, Post
from .forms import CustomerDataForm, MusubiyaUserForm,  ListSearchForm, DetailDataForm, PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, Count
from django.contrib import messages
import math, collections, datetime, itertools
from dateutil.relativedelta import relativedelta
from datetime import date, timedelta
from . import use_selenium

now_term = 9 #決算期が変わったら変えること


# Create your views here.

# ページネーション用
def paginate_queryset(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

def index(request):
    return redirect('accounts:login')

# トップ画面【完了】
@login_required
def user_detail(request, pk):
    this_year = datetime.date.today().year
    this_month = datetime.date.today().month
    prospect = CustomerData.objects.filter(user_id=request.user.id)  #見込み客obj
    # 今月売上目標
    mandatory_list = {10:'mandatory_Oct', 11:'mandatory_Nov', 12:'mandatory_Dec', 1:'mandatory_Jan', 2:'mandatory_Feb', 3:'mandatory_Mar', 4:'mandatory_Apr', 5:'mandatory_May', 6:'mandatory_Jun', 7:'mandatory_Jul', 8:'mandatory_Aug', 9:'mandatory_Sep'}
    stretch_list = {10:'stretch_Oct', 11:'stretch_Nov', 12:'stretch_Dec', 1:'stretch_Jan', 2:'stretch_Feb', 3:'stretch_Mar', 4:'stretch_Apr', 5:'stretch_May', 6:'stretch_Jun', 7:'stretch_Jul', 8:'stretch_Aug', 9:'stretch_Sep'}
    md = mandatory_list[this_month]
    sd = stretch_list[this_month]
    if MusubiyaUser.objects.filter(musubiya_user_id=request.user.id, term=now_term).exists():
        mandatory_goal = MusubiyaUser.objects.values_list(md, flat=True).get(musubiya_user_id=request.user.id, term=now_term)
        stretch_goal = MusubiyaUser.objects.values_list(sd, flat=True).get(musubiya_user_id=request.user.id, term=now_term)
    else:
        mandatory_goal = 0
        stretch_goal = 0
    # 必達達成率計算
    mandatory_now_list = []
    mandatory_now_bf = prospect.filter(bf_payment_nen=this_year,bf_payment_month=this_month)
    mandatory_now_ad = prospect.filter(ad_payment_nen=this_year, ad_payment_month=this_month)
    for mnbf in mandatory_now_bf:
        mandatory_now_list.append(mnbf.bf_payment_amount)
    for mnad in mandatory_now_ad:
        mandatory_now_list.append(mnad.ad_payment_amount)
    mnl = sum(mandatory_now_list)
    if mandatory_goal == 0:
        mat = 0  #mandatory_achievement_rate
    else:
        mat = mnl / mandatory_goal *100   #mandatory_achievement_rate

    # ストレッチ達成率計算
    stretch_now_list = []
    stretch_now_bf = prospect.filter(bf_payment_nen=this_year,bf_payment_month=this_month)
    stretch_now_ad = prospect.filter(ad_payment_nen=this_year, ad_payment_month=this_month)
    for stbf in stretch_now_bf:
        stretch_now_list.append(stbf.bf_payment_amount)
    for stad in stretch_now_ad:
        stretch_now_list.append(stad.ad_payment_amount)
    stl = sum(stretch_now_list)
    if stretch_goal == 0:
        sat = 0  #stretch_achievement_rate
    else:
        sat = stl / stretch_goal *100   #stretch_achievement_rate

    # Todoリスト
    posts = Post.objects.filter(user_id=request.user.id)
    form = PostForm()
    if 'new' in request.POST:
        form = PostForm()
        obj = Post()
        post = PostForm(request.POST, instance=obj)
        post.save()
        return redirect('c_data:user_detail', pk=request.user.id)
    if 'del' in request.POST:
        post = Post.objects.get(id=request.POST['del'])
        post.delete()
        return redirect('c_data:user_detail', pk=request.user.id)

    # 解約３ヶ月前取得
    list_3_key = []
    list_3_value = []
    for pro in prospect:
        threeMonthAgo_m = pro.contract_end_month - 3
        threeMonthAgo_y = pro.contract_end_year
        if threeMonthAgo_m <=3:
            threeMonthAgo_m = pro.contract_end_month + 12 - 3
            threeMonthAgo_y = pro.contract_end_year - 1
        if threeMonthAgo_m == this_month and threeMonthAgo_y == this_year:
            list_3_key.append(pro.id)
            list_3_value.append(pro.customer_name)
    l = dict(zip(list_3_key,list_3_value))

    # 誕生日検索
    prospect_bd = prospect.filter(birthday__month=(this_month))
    prospect_pbd = prospect.filter(partner_birthday__month=(this_month))
    prospect_c1bd = prospect.filter(child1_birthday__month=(this_month))
    prospect_c2bd = prospect.filter(child2_birthday__month=(this_month))


    login_user = request.user
    if pk == login_user.id:
        user = User.objects.get(pk=pk)
        context = {
            'user': user,
            'this_year': this_year,
            'this_month': this_month,
            'mandatory_goal': mandatory_goal,
            'mat': mat,
            'stretch_goal': stretch_goal,
            'sat': sat,
            'posts': posts,
            'form': form,
            'l': l,
            'prospect_bd':prospect_bd,
            'prospect_pbd':prospect_pbd,
            'prospect_c1bd':prospect_c1bd,
            'prospect_c2bd':prospect_c2bd,
        }
        return render(request, 'c_data/users_detail.html', context)
    else:
        return redirect('accounts:logout')

# プロフィール画面【完了】
@login_required
def profile(request, pk):
    if request.method == 'GET':
        login_user = request.user
        # フォームに初期値を流し込む
        if 'term' in request.session:
            term_name = request.session['term']
            u_data = MusubiyaUser.objects.get(musubiya_user_id=request.user.id, term=term_name[0])
            form = MusubiyaUserForm(initial={
                "rank":u_data.rank,
                "plan":u_data.plan,
                'term':u_data.term,
                "mandatory_Oct":u_data.mandatory_Oct,
                "mandatory_Nov":u_data.mandatory_Nov,
                "mandatory_Dec":u_data.mandatory_Dec,
                "mandatory_Jan":u_data.mandatory_Jan,
                "mandatory_Feb":u_data.mandatory_Feb,
                "mandatory_Mar":u_data.mandatory_Mar,
                "mandatory_Apr":u_data.mandatory_Apr,
                "mandatory_May":u_data.mandatory_May,
                "mandatory_Jun":u_data.mandatory_Jun,
                "mandatory_Jul":u_data.mandatory_Jul,
                "mandatory_Aug":u_data.mandatory_Aug,
                "mandatory_Sep":u_data.mandatory_Sep,
                "stretch_Oct":u_data.stretch_Oct,
                "stretch_Nov":u_data.stretch_Nov,
                "stretch_Dec":u_data.stretch_Dec,
                "stretch_Jan":u_data.stretch_Jan,
                "stretch_Feb":u_data.stretch_Feb,
                "stretch_Mar":u_data.stretch_Mar,
                "stretch_Apr":u_data.stretch_Apr,
                "stretch_May":u_data.stretch_May,
                "stretch_Jun":u_data.stretch_Jun,
                "stretch_Jul":u_data.stretch_Jul,
                "stretch_Aug":u_data.stretch_Aug,
                "stretch_Sep":u_data.stretch_Sep
            })
            # 合計の計算
            mandatory_sum = u_data.mandatory_Oct + u_data.mandatory_Nov + u_data.mandatory_Dec + u_data.mandatory_Jan + u_data.mandatory_Feb + u_data.mandatory_Mar + u_data.mandatory_Apr + u_data.mandatory_May + u_data.mandatory_Jun + u_data.mandatory_Jul + u_data.mandatory_Aug + u_data.mandatory_Sep
            stretch_sum = u_data.stretch_Oct + u_data.stretch_Nov + u_data.stretch_Dec + u_data.stretch_Jan + u_data.stretch_Feb + u_data.stretch_Mar + u_data.stretch_Apr + u_data.stretch_May + u_data.stretch_Jun + u_data.stretch_Jul + u_data.stretch_Aug + u_data.stretch_Sep
        elif MusubiyaUser.objects.filter(musubiya_user_id=request.user.id).exists():
            u_data = MusubiyaUser.objects.get(musubiya_user_id=request.user.id, term=now_term)
            form = MusubiyaUserForm(initial={
                "rank":u_data.rank,
                "plan":u_data.plan,
                'term':u_data.term,
                "mandatory_Oct":u_data.mandatory_Oct,
                "mandatory_Nov":u_data.mandatory_Nov,
                "mandatory_Dec":u_data.mandatory_Dec,
                "mandatory_Jan":u_data.mandatory_Jan,
                "mandatory_Feb":u_data.mandatory_Feb,
                "mandatory_Mar":u_data.mandatory_Mar,
                "mandatory_Apr":u_data.mandatory_Apr,
                "mandatory_May":u_data.mandatory_May,
                "mandatory_Jun":u_data.mandatory_Jun,
                "mandatory_Jul":u_data.mandatory_Jul,
                "mandatory_Aug":u_data.mandatory_Aug,
                "mandatory_Sep":u_data.mandatory_Sep,
                "stretch_Oct":u_data.stretch_Oct,
                "stretch_Nov":u_data.stretch_Nov,
                "stretch_Dec":u_data.stretch_Dec,
                "stretch_Jan":u_data.stretch_Jan,
                "stretch_Feb":u_data.stretch_Feb,
                "stretch_Mar":u_data.stretch_Mar,
                "stretch_Apr":u_data.stretch_Apr,
                "stretch_May":u_data.stretch_May,
                "stretch_Jun":u_data.stretch_Jun,
                "stretch_Jul":u_data.stretch_Jul,
                "stretch_Aug":u_data.stretch_Aug,
                "stretch_Sep":u_data.stretch_Sep
            })
            # 合計の計算
            mandatory_sum = u_data.mandatory_Oct + u_data.mandatory_Nov + u_data.mandatory_Dec + u_data.mandatory_Jan + u_data.mandatory_Feb + u_data.mandatory_Mar + u_data.mandatory_Apr + u_data.mandatory_May + u_data.mandatory_Jun + u_data.mandatory_Jul + u_data.mandatory_Aug + u_data.mandatory_Sep

c_data/templates/c_data/data.html
{% extends 'c_data/base.html' %}

{% block content %}
<div id="wrapper">
    <!--BEGIN SIDEBAR MENU-->
    <nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
        <div class="sidebar-collapse menu-scroll">
            <ul id="side-menu" class="nav">
                <div class="clearfix"></div>
                <li><a href="{% url 'c_data:user_detail' pk=user.id %}"><i class="fa fa-tachometer fa-fw">
                      <div class="icon-bg bg-orange"></div>
                  </i><span class="menu-title">Dashboard</span></a></li>
                <li><a href="{% url 'c_data:list' pk=user.id %}"><i class="fa fa-desktop fa-fw">
                      <div class="icon-bg bg-green"></div>
                  </i><span class="menu-title">顧客一覧</span></a>
                </li>
                <li><a href="{% url 'c_data:new_data' pk=user.id %}"><i class="fa fa-edit fa-fw">
                      <div class="icon-bg bg-violet"></div>
                  </i><span class="menu-title">新規登録</span></a>
                </li>
                <li><a href="{% url 'c_data:prospect' pk=user.id %}"><i class="fa fa-th-list fa-fw">
                      <div class="icon-bg bg-blue"></div>
                  </i><span class="menu-title">見込管理</span></a>
                </li>
                <li><a href="{% url 'c_data:progress' pk=user.id %}"><i class="fa fa-clock-o fa-fw">
                      <div class="icon-bg bg-red"></div>
                  </i><span class="menu-title">進捗管理</span></a>
                </li>
                <li  class="active"><a href="{% url 'c_data:data' pk=user.id %}"><i class="fa fa-user fa-fw">
                      <div class="icon-bg bg-red"></div>
                  </i><span class="menu-title">紹介管理</span></a>
                </li>
                <li><a href="{% url 'c_data:budget_control' pk=user.id %}"><i class="fa fa-bar-chart-o fa-fw">
                      <div class="icon-bg bg-red"></div>
                  </i><span class="menu-title">予実管理</span></a>
                </li>
                <li><a href="{% url 'reservation:index' %}"><i class="fa fa-calendar fa-fw">
                      <div class="icon-bg bg-red"></div>
                  </i><span class="menu-title">設備予約へ</span></a>
                </li>
            </ul>
        </div>
    </nav>
    <!--END SIDEBAR MENU-->
    <!--BEGIN PAGE WRAPPER-->
    <div id="page-wrapper">
        <!--BEGIN TITLE & BREADCRUMB PAGE-->
        <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
            <div class="page-header pull-left">
                <div class="page-title">紹介管理</div>
            </div>
            <ol class="breadcrumb page-breadcrumb pull-right">
                <li><i class="fa fa-home"></i>&nbsp;<a href="{% url 'c_data:user_detail' pk=user.id %}">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
                <li class="active"><a href="{% url 'c_data:data' pk=user.id %}">紹介管理</a></li>
            </ol>
            <div class="clearfix">
            </div>
        </div>
        <!--END TITLE & BREADCRUMB PAGE-->
        <!--BEGIN CONTENT-->
        <div class="page-content">
            <div id="tab-general">
                <div class="row mbl">
                    <div class="col-lg-12">
                        <div class="col-md-12">
                            <div id="area-chart-spline" style="width: 100%; height: 300px; display: none;">
                            </div>
                        </div>
                    </div>
                    <!-- 検索ナビ -->
                    <div class="row">
                      <div class="col-lg-12">
                          <nav role="navigation" class="navbar navbar-default">
                              <div class="container-fluid">
                                  <div class="navbar-header">
                                      <a class="navbar-brand">検索</a></div>
                                  <div id="bs-example-navbar-collapse-2" class="collapse navbar-collapse">
                                      <form action="" method="POST" role="search" class="navbar-form navbar-left">
                                          {% csrf_token %}
                                          <div class="form-group">
                                            紹介月検索：{{ form.introduce_year }}{{ form.introduce_month }}
                                          </div>
                                          &nbsp;
                                          <button type="submit" name="intro" class="btn btn-blue">検索</button>
                                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                          <button type="submit" name="clear" class="btn btn-blue">クリア</button>
                                      </form>
                                  </div>
                              </div>
                          </nav>
                      </div>
                    </div>
                    <!-- END検索ナビ -->
                    <div class="col-lg-12">
                        <div class="row">
                          <div class="col-lg-3">
                              <div class="panel panel-green">
                                  <div class="panel-heading">月別紹介数【{{ this_year }}年{{ this_month }}月】
                                  </div>
                                  <div class="panel-body">
                                  <table class="table table-hover table-bordered">
                                    <thead>
                                      <tr>
                                        <th>お客様名</th>
                                        <th>紹介者名</th>
                                        <th>関係性</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      {% for  mi in monthly_introduce %}
                                      <tr>
                                          <td>
                                            <a href="{% url 'c_data:detail' pk=user.id CustomerData_id=mi.id %}">
                                              {{ mi.customer_name }}
                                            </a>
                                          </td>
                                          <td>
                                            <a href="{% url 'c_data:detail' pk=user.id CustomerData_id=mi.id %}">
                                              {{ mi.introducer_name }}
                                            </a>
                                          </td>
                                          <td>
                                            <a href="{% url 'c_data:detail' pk=user.id CustomerData_id=mi.id %}">
                                              {{ mi.introduction_type }}
                                            </a>
                                          </td>
                                      </tr>
                                      {% endfor %}
                                    </tbody>
                                  </table>
                                </div>
                              </div>
                            </div>
                    <div class="col-lg-3">
                        <div class="panel panel-red">
                            <div class="panel-heading">紹介者一覧【累計】
                            </div>
                            <div class="panel-body">
                            <table class="table table-hover table-bordered">
                              <thead>
                                <tr>
                                  <th>紹介者名</th>
                                  <th>紹介数</th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for  l in page_obj %}
                                {% for  key, value in l.items %}
                                <tr>
                                    <td>{{ key }}</td>
                                    <td>{{ value }}&nbsp;&nbsp;人</td>
                                </tr>
                              </tbody>
                                {% endfor %}
                                {% endfor %}
                            </table>
                            <ul class="pagination">
                            <!-- 前へ の部分 -->
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif %}

                            <!-- 数字の部分 -->
                            {% for num in page_obj.paginator.page_range %}
                                {% if page_obj.number == num %}
                                    <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                {% endif %}
                            {% endfor %}

                            <!-- 次へ の部分 -->
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                            </ul>
                        </div>
                      </div>
                    </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
          </div>
        </div>
      </div>
    </div>
    <!--END CONTENT-->
</div>
<!--END PAGE WRAPPER-->
</div>
</div>
{% endblock %}

c_data/templates/c_data/list.html
{% extends 'c_data/base.html' %}

{% block content %}
<div id="wrapper">
    <!--BEGIN SIDEBAR MENU-->
    <nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
        <div class="sidebar-collapse menu-scroll">
            <ul id="side-menu" class="nav">
                <div class="clearfix"></div>
                <li><a href="{% url 'c_data:user_detail' pk=user.id %}"><i class="fa fa-tachometer fa-fw">
                        <div class="icon-bg bg-orange"></div>
                    </i><span class="menu-title">Dashboard</span></a></li>
                <li class="active"><a href="{% url 'c_data:list' pk=user.id %}"><i class="fa fa-desktop fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">顧客一覧</span></a>
                </li>
                <li><a href="{% url 'c_data:new_data' pk=user.id %}"><i class="fa fa-edit fa-fw">
                        <div class="icon-bg bg-violet"></div>
                    </i><span class="menu-title">新規登録</span></a>
                </li>
                <li><a href="{% url 'c_data:prospect' pk=user.id %}"><i class="fa fa-th-list fa-fw">
                        <div class="icon-bg bg-blue"></div>
                    </i><span class="menu-title">見込管理</span></a>
                </li>
                <li><a href="{% url 'c_data:progress' pk=user.id %}"><i class="fa fa-clock-o fa-fw">
                      <div class="icon-bg bg-red"></div>
                  </i><span class="menu-title">進捗管理</span></a>
                </li>
                <li><a href="{% url 'c_data:data' pk=user.id %}"><i class="fa fa-user fa-fw">
                      <div class="icon-bg bg-red"></div>
                  </i><span class="menu-title">紹介管理</span></a>
                </li>
                <li><a href="{% url 'c_data:budget_control' pk=user.id %}"><i class="fa fa-bar-chart-o fa-fw">
                      <div class="icon-bg bg-red"></div>
                  </i><span class="menu-title">予実管理</span></a>
                </li>
                <li><a href="{% url 'reservation:index' %}"><i class="fa fa-calendar fa-fw">
                      <div class="icon-bg bg-red"></div>
                  </i><span class="menu-title">設備予約へ</span></a>
                </li>
            </ul>
        </div>
    </nav>
    <!--END SIDEBAR MENU-->
    <!--BEGIN PAGE WRAPPER-->
    <div id="page-wrapper">
        <!--BEGIN TITLE & BREADCRUMB PAGE-->
        <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
            <div class="page-header pull-left">
                <div class="page-title">顧客一覧</div>
            </div>
            <ol class="breadcrumb page-breadcrumb pull-right">
                <li><i class="fa fa-home"></i>&nbsp;<a href="{% url 'c_data:user_detail' pk=user.id %}">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
                <li class="active"><a href="{% url 'c_data:list' pk=user.id %}">顧客一覧</a></li>
            </ol>
            <div class="clearfix">
            </div>
        </div>
        <!--END TITLE & BREADCRUMB PAGE-->
        <!--BEGIN CONTENT-->
        <div class="page-content">
            <div id="tab-general">
                <div class="row mbl">
                    <div class="col-lg-12">
                        <div class="col-md-12">
                            <div id="area-chart-spline" style="width: 100%; height: 300px; display: none;"></div>
                        </div>
                    </div>
                    <!-- 検索ナビ -->
                    <div class="row">
                      <div class="col-lg-12">
                          <nav role="navigation" class="navbar navbar-default">
                              <div class="container-fluid">
                                  <div class="navbar-header">
                                      <a class="navbar-brand">検索</a></div>
                                  <div id="bs-example-navbar-collapse-2" class="collapse navbar-collapse">
                                      <form action="" method="POST" role="search" class="navbar-form navbar-left">
                                          {% csrf_token %}
                                          <div class="form-group">
                                            お客様名：{{ form.customer_name }}
                                          </div>
                                          &nbsp;
                                          <button type="submit" name='c_name' class="btn btn-blue">検索</button>
                                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                          <div class="form-group">
                                            申込み予定：{{ form.apply_year }}{{ form.apply_month }}
                                          </div>
                                          &nbsp;
                                          <button type="submit" name="apply" class="btn btn-blue">検索</button>
                                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                          <button type="submit" name="clear" class="btn btn-blue">クリア</button>
                                      </form>
                                  </div>
                              </div>
                          </nav>
                      </div>
                    </div>
                    <!-- END検索ナビ -->
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-12">
                              <div class="panel panel-green">
                                <div class="panel-heading">
                                </div>
                                <div class="panel-body">
                                    <table class="table table-hover table-bordered">
                                        <thead>
                                        <tr>
                                            <th>お客様名</th>
                                            <th>状況</th>
                                            <th>申込予定</th>
                                            <th>紹介者名</th>
                                            <th>備考</th>
                                            <th>削除<th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for c_data in page_obj %}
                                          <tr class="active">
                                              <td><a href="{% url 'c_data:detail' pk=user.id CustomerData_id=c_data.id %}">{{ c_data.customer_name }}</a></td>
                                              <td><a href="{% url 'c_data:detail' pk=user.id CustomerData_id=c_data.id %}">{{ c_data.status }}</a></td>
                                              <td><a href="{% url 'c_data:detail' pk=user.id CustomerData_id=c_data.id %}">{{ c_data.apply_year }}年{{ c_data.apply_month }}月</a></td>
                                              <td><a href="{% url 'c_data:detail' pk=user.id CustomerData_id=c_data.id %}">{{ c_data.introducer_name }}</a></td>
                                              <td><a href="{% url 'c_data:detail' pk=user.id CustomerData_id=c_data.id %}">{{ c_data.remarks }}</a></td>
                                              <td><input type=button value="削除"></td>
                                          </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                    <ul class="pagination">
                                    <!-- 前へ の部分 -->
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                    {% endif %}

                                    <!-- 数字の部分 -->
                                    {% for num in page_obj.paginator.page_range %}
                                        {% if page_obj.number == num %}
                                            <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                        {% endif %}
                                    {% endfor %}

                                    <!-- 次へ の部分 -->
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
    <!--END CONTENT-->
</div>
<!--END PAGE WRAPPER-->
</div>
</div>
{% endblock %}